### ISSUE TITLE
Set LC_NUMERIC in qt project

### ISSUE THREAD

**Issue by fvitello** [NEANIAS-Space/ViaLacteaVisualAnalytics#11]

**Comment by fvitello** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Settare LC_NUMERIC dal file pro](https://trello.com/c/K3AmlmaU/7-settare-lcnumeric-dal-file-pro)

**Comment by fvitello** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sistemare lo script runApp.sh della release ubuntu](https://trello.com/c/SZtjuwvU/8-sistemare-lo-script-runappsh-della-release-ubuntu)

**Comment by GTudisco** [comment]
Related commit: https://github.com/NEANIAS-Space/ViaLacteaVisualAnalytics/commit/eabcf93f2e44561c6841c34a4b82deae69491829
