### ISSUE TITLE
Fix deb file

### ISSUE THREAD

**Issue by fvitello** [NEANIAS-Space/ViaLacteaVisualAnalytics#12]

**Comment by fvitello** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sistemare lo script runApp.sh della release ubuntu](https://trello.com/c/SZtjuwvU/8-sistemare-lo-script-runappsh-della-release-ubuntu)

**Comment by GTudisco** [comment]
Fixed in release 1.1
