### ISSUE TITLE
Update User Manual

### ISSUE THREAD

**Issue by fvitello** [NEANIAS-Space/ViaLacteaVisualAnalytics#8]

**Comment by fvitello** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Aggiornare il manuale utente](https://trello.com/c/QOusmEgz/11-aggiornare-il-manuale-utente)

**Comment by GTudisco** [comment]
The user manual is now on ReadTheDocs [here](https://vlva.readthedocs.io/).
