### ISSUE TITLE
Create readthedocs documentation

### ISSUE THREAD

**Issue by fvitello** [NEANIAS-Space/ViaLacteaVisualAnalytics#9]

**Comment by fvitello** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Readthedocs documentation](https://trello.com/c/2WRqENUs/14-readthedocs-documentation)

**Comment by GTudisco** [comment]
Documentation URL: https://vlva.readthedocs.io/
Documentation source: https://github.com/NEANIAS-Space/ViaLacteaVisualAnalytics-doc
